AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics:
  Exclude:
    - '**/raise_http_exception.rb'

Metrics/ClassLength:
  Exclude:
    - '**/get_sensors.rb'